name: LoveTrades
version: '${version}'

main: me.lovelace.loveTrades.LoveTrades
api-version: '26.2'
load: POSTWORLD

authors: [ Lovelace ]

softdepend: [ LuckPerms, PlaceholderAPI, LoveCore ]

commands:
  trade:
    description: "Начать торговлю с другим игроком"
    aliases: [ lovetrades, торговля ]
    usage: "/trade <игрок|accept|deny|toggle>"
    permission: axtrades.use
  lovetradesadmin:
    description: "Административные команды торговли"
    aliases: [ tradeadmin ]
    usage: "/lovetradesadmin <reload|modifier>"
    permission: axtrades.admin

permissions:
  axtrades.use:
    description: "Разрешает использование команды /trade"
    default: true
  axtrades.bypass.tax:
    description: "Полный обход любых комиссий и налогов"
    default: false
  axtrades.bypass.combat:
    description: "Разрешает торговать, находясь в PvP"
    default: false
  axtrades.bypass.cooldown:
    description: "Обход кулдауна между торговлями с одним и тем же игроком"
    default: false
  axtrades.bypass.stack-limit:
    description: "Обход лимита стаков за одну торговлю"
    default: false
  axtrades.admin:
    description: "Административные команды торговли"
    default: op
