name: LoveTrades
version: '${version}'

main: me.lovelace.loveTrades.LoveTrades
api-version: '1.21.11'
load: POSTWORLD

authors: [ Lovelace ]

softdepend: [ LuckPerms ]

commands:
  trade:
    description: "Начать торговлю с другим игроком"
    aliases: [ торговля ]
    usage: "/trade <игрок>"
    permission: axtrades.use
  tradeadmin:
    description: "Административные команды торговли"
    usage: "/tradeadmin <modifier|reload>"
    permission: axtrades.admin

permissions:
  axtrades.use:
    description: "Разрешает использование команды /trade"
    default: true
  axtrades.bypass.tax:
    description: "Полный обход любых комиссий и налогов"
    default: false
  axtrades.bypass.combat:
    description: "Разрешает торговать, находясь в PvP"
    default: false
  axtrades.bypass.cooldown:
    description: "Обход кулдауна между торговлями с одним и тем же игроком"
    default: false
  axtrades.bypass.stack-limit:
    description: "Обход лимита стаков за одну торговлю"
    default: false
  axtrades.admin:
    description: "Административные команды торговли"
    default: op
