name: LoveTrades
version: '${version}'

main: me.lovelace.loveTrades.LoveTrades
api-version: '1.21.11'
load: POSTWORLD

authors: [ Lovelace ]

softdepend: [ LuckPerms, PlaceholderAPI ]

commands:
  trade:
    description: "Начать торговлю с другим игроком"
    aliases: [ торговля ]
    usage: "/trade <игрок|accept|deny|toggle>"
    permission: axtrades.use
  tradeadmin:
    description: "Административные команды торговли"
    usage: "/tradeadmin <modifier|reload>"
    permission: axtrades.admin

permissions:
  axtrades.use:
    description: "Разрешает использование команды /trade"
    default: true
  axtrades.bypass.tax:
    description: "Полный обход любых комиссий и налогов"
    default: false
  axtrades.admin:
    description: "Административные команды торговли"
    default: op
